---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
    app.kubernetes.io/instance: homepage
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: homepage
    app.kubernetes.io/instance: homepage
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
