---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamripper
  namespace: streamripper
  labels:
    app.kubernetes.io/name: streamripper
    app.kubernetes.io/instance: streamripper
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: streamripper
      app.kubernetes.io/instance: streamripper
  template:
    metadata:
      labels:
        app.kubernetes.io/name: streamripper
        app.kubernetes.io/instance: streamripper
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
        - name: streamripper
          image: ghcr.io/maltebiermann/streamripper:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Europe/Berlin
          ports:
            - containerPort: 8001
              name: control
              protocol: TCP
          volumeMounts:
            - name: music
              mountPath: /workspace/streamripper/music
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
      volumes:
        - name: music
          persistentVolumeClaim:
            claimName: streamripper-music
