---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nginx-helloworld
  - longhorn
  - traefik
  - metallb/metallb-kustomization.yaml
  - metallb/metallb-config-kustomization.yaml
  - mosquitto
  - booklore
  - shelfmark
