---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homeassistant-config
  namespace: homeassistant
data:
  configuration.yaml: |
    homeassistant:    
    frontend:
    
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.0.0.0/8
        - 127.0.0.1
        - ::1
    
    mobile_app:
    
    homekit:
      port: 21063
      ip_address: 0.0.0.0
      advertise_ip: 10.0.10.102
