---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homeassistant-config
  namespace: homeassistant
data:
  configuration.yaml: |
    homeassistant:
      name: Home
      latitude: 52.5
      longitude: 13.4
      unit_system: metric
      time_zone: Europe/Berlin
    
    frontend:
    
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.0.0.0/8
        - 127.0.0.1
        - ::1
    
    mobile_app:
