---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: homeassistant
  labels:
    app: homeassistant
spec:
  type: ClusterIP
  ports:
  - port: 8123
    targetPort: 8123
    protocol: TCP
    name: http
  - port: 5353
    targetPort: 5353
    protocol: UDP
    name: mdns
  - port: 21064
    targetPort: 21064
    protocol: TCP
    name: homekit
  selector:
    app: homeassistant
