---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: streamripper-next-data
  namespace: streamripper-next
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
